### ISSUE TITLE
css hack not work 

### ISSUE THREAD

**Issue by AnnVoV** [jonathanepollack/gulp-minify-css#101]
Hi~ 
    if I use * or unquote('30% 25%\0') in styl, it will not work well after I use gulp-minify-css
   and if I use minifycss({compatibility: 'ie8'}  it can only preserve * ,but it can't preserve \0

**Comment by shinnn** [comment]
https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977

Thanks for trying to contribute the open source project though.
