### ISSUE TITLE
BUG: skip-import setting of clean-css doesn't seem to ignore @import declaration

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jonathanepollack/gulp-minify-css#103]
I seem to be getting frequent errors when the plugin reaches an `@import` declaration. 

*Error*
```
 Error in plugin 'gulp-minify-css'
Message:
    Broken @import declaration of "https://fonts.googleapis.com/css?family=Lobster" - timeout
```

So based on the [Clean-CSS](https://github.com/jakubpawlowicz/clean-css) documentation, I used `--skip-import` setting when calling `minifycss()` function. 

`.pipe(minifycss({skip_import: true}))`

when running gulp tasks I still am getting this errors.

**Comment by abishekrsrikaanth** [comment]
nvm, it was a typo error.

**Comment by AndrewEastwood** [comment]
so, how to solve this?

**Comment by shinnn** [comment]
@AndrewEastwood https://github.com/murphydanger/gulp-minify-css/issues/8#issuecomment-37887694
