### ISSUE TITLE
keepSpecialComments does not work at all

### ISSUE THREAD

**Issue by herrbischoff** [jonathanepollack/gulp-minify-css#104]
**Note:** This is a re-post of an issue I raised in the `clean-css` repo [here](https://github.com/jakubpawlowicz/clean-css/issues/584).

I'm using clean-css within a `gulp` workflow (via `gulp-cssmin`) but the `keepSpecialComments` option is not honored. By default, all special comments should be preserved but instead they are stripped. If I run it with an additional option, this additional option is honored. Like so:

```coffee
.pipe cssmin
  keepSpecialComments: 1
  keepBreaks: true
```

The linebreaks are there but all special comments have been stripped out.

```coffee
.pipe cssmin
  keepBreaks: true
```

This gives the exact same result.

**Comment by shinnn** [comment]
```js
'use strict';

var File = require('vinyl');
var gulpMinifyCss = require('gulp-minify-css');

gulpMinifyCss()
.on('data', function(file) {
  console.log(file.contents.toString());
})
.end(new File({contents: new Buffer('/*! 1 */a{color:red}/*! 2 */')}))
```

gulp-minify-css produces exactly the same result as https://github.com/jakubpawlowicz/clean-css/issues/584#issuecomment-105808077.

Additionaly,

1. Please do not report gulp-cssmin issues here. This plugin is *gulp-minify-css*.
2. You should not use gulp-cssmin since it's blacklisted. https://github.com/gulpjs/plugins/blob/8b21964fd6b794c47ec93c82c2df38cf52c53c5c/src/blackList.json#L76

**Comment by herrbischoff** [comment]
My bad, I did not change cssmin to gulp-minify-css in my issue report. However, the result is exactly the same as described above. Here's a more complete excerpt from my `gulpfile`:

```coffee
gulp = require 'gulp'
minifyCss = require 'gulp-minify-css'

gulp.task 'stylus', ->
  gulp.src paths.styles.input
    .pipe stylus()
    .pipe minifyCss
      keepSpecialComments: 1
      keepBreaks: true
    .pipe gulp.dest paths.styles.output
```

**Comment by shinnn** [comment]
@herrbischoff, https://github.com/jakubpawlowicz/clean-css/issues/584#issuecomment-105955540

**Comment by shinnn** [comment]
```js
'use strict';

var File = require('vinyl');
var gulpMinifyCss = require('.');

gulpMinifyCss({
  keepSpecialComments: 1,
  keepBreaks: true
})
.on('data', function(file) {
  file.contents.toString(); //=> '/*! 1 */\na{color:red}'
})
.end(new File({contents: new Buffer('/*! 1 */\na{color:red}/*! 2 */')}))
```

In this small example both `keepBreaks` and `keepSpecialComments` works correctly.

**Comment by herrbischoff** [comment]
That may be, but does the above `gulpfile` example work for you? My main gripe is that even if I do the basic

```coffee
gulp = require 'gulp'
stylus = require 'gulp-stylus'
minifyCss = require 'gulp-minify-css'

gulp.task 'stylus', ->
  gulp.src paths.styles.input
    .pipe stylus()
    .pipe minifyCss()
    .pipe gulp.dest paths.styles.output
```

all special comments get stripped away.

**Comment by shinnn** [comment]
Ah, OK I found the cause. Stylus changes all special comments to normal comments and you can see how to fix it here: https://github.com/stylus/stylus/issues/1763

**Comment by herrbischoff** [comment]
Phew. Thanks a lot for taking the time to dig through Stylus issues! I tried the solution you linked to and it works beautifully. And again it shows how a single missing char can break everything.

**Comment by shinnn** [comment]
Now you can close https://github.com/jakubpawlowicz/clean-css/issues/584 since that's not actually related to clean-css :)

**Comment by herrbischoff** [comment]
Done and done. :) Thanks again. This was driving me nuts.
