### ISSUE TITLE
Minify with sourcemaps

### ISSUE THREAD

**Issue by jblandry** [jonathanepollack/gulp-minify-css#34]
Hi,

I'm trying to minify my compass-compiled css and keep the sourcemap generated, but it does not seem to work because the sourcemap doesn't change after the minifying.

This pattern doesn't seem to be implemented in your plugin:
https://github.com/floridoo/gulp-sourcemaps#plugin-developers-only-how-to-add-source-map-support-to-plugins

Thanks in advance

```
#-- Compile via Compass
gulp.task 'styles_compass', ->
	compass = require 'gulp-compass'

	gulp.src ''../common/bundles/*.scss'
		.pipe compass
			css: '../build/styles'
			sass: '../common/bundles'
			sourcemap: true
		.on('error', ->)

#-- Minify
gulp.task 'styles_minify', ['styles_compass'], ->
	minifycss  = require 'gulp-minify-css'
	sourcemaps = require 'gulp-sourcemaps'

	gulp.src '../build/styles/*.css'
		.pipe sourcemaps.init loadMaps:true
		.pipe minifycss()
		.pipe sourcemaps.write
			addComment: true
			includeContent: false
		.pipe gulp.dest '../build/styles"
```

**Comment by mnpenner** [comment]
:+1:  Everything else in my CSS chain now supports source maps; this is the missing link.

**Comment by davidangel** [comment]
+1 for sourcemap support

**Comment by rightaway** [comment]
+1

**Comment by DominicBarnard** [comment]
BOOOM... [Sourcemaps!](https://github.com/jonathanepollack/gulp-minify-css/pull/57)
Give it a go and let me know if works.

**Comment by marvinroger** [comment]
Thanks guys, sourcemaps are now working great as of 0.3.13, available now on npm. :+1:

**Comment by mnpenner** [comment]
Works great. Thank you !
