### ISSUE TITLE
0.2s becomes .2s

### ISSUE THREAD

**Issue by cjcheshire** [jonathanepollack/gulp-minify-css#54]
Hi

I'm having some issues with my values and wondered if there is a feature beyond "noAdvanced" that would prevent them from being changed?

I know this would preventing further minifying, just wondered :)

**Comment by jonathanepollack** [comment]
This is a `clean-css` issue.

**Comment by cjcheshire** [comment]
My apologies.

**Comment by jonathanepollack** [comment]
No worries.
