### ISSUE TITLE
Concatenating Sass files before minifying?

### ISSUE THREAD

**Issue by rightaway** [jonathanepollack/gulp-minify-css#60]
Is is possible to get the sourcemaps feature of gulp-minify-css working if you are concatenating the Sass files first? For example if I do it like this, the browser shows the lines from the concat.scss file. Is it possible to have the browser show the lines from the original .scss files (the ones used for concatenation) where the line came from?

Or am I totally misunderstanding how this all works, because the sourcemap file seems to be getting written out by the rubySass() line bbelow and not sourcemaps.write()?

```
            .pipe(sourcemaps.init())
            .pipe(concat('concat.scss'))
            .pipe(rubySass())
            .pipe(cssMapFilter)  // Filter out the concat.css.map
            .pipe(rename('min.css'))
            .pipe(minifyCss())
            .pipe(sourcemaps.write())
            .pipe(gulp.dest(dest))
```

**Comment by jonathanepollack** [comment]
Sounds like two levels of transformations. I.e you want to go from this:
```
Sass => css => min'd css
```
to this in the browser
```
min'd css => Sass
```
?

**Comment by rightaway** [comment]
I guess it is 2 transformations, or maybe more because of concatenation. Can you think of any way that such a setup could work?

I could save the minification just for prod not dev, but in dev wouldn't the source maps still show me the lines in the concatenated Sass rather than the source Sass?

**Comment by jonathanepollack** [comment]
Nothing really comes to mind. Maybe you should try to googling around for some plugin recipes that handle this. If you find any, feel free to throw them down here.
