### ISSUE TITLE
v0.3.12 breaks tasks

### ISSUE THREAD

**Issue by Stichoza** [jonathanepollack/gulp-minify-css#61]
I don't know what exactly is the problem, but `v0.3.12` breaks tasks. I have downgraded to `v0.3.11` and it works fine as it did usually.

And I'm not the only one. @thepuzzlemaster wrote it in https://github.com/jonkemp/gulp-useref/issues/44 (here I found the version issue)

Here is my [`package.json`](https://github.com/Stichoza/emul.ge/blob/8a63b8e1ed4b0ca43a32056d10d22cde7709085f/package.json#L27) and [`gulpfile.coffee`](https://github.com/Stichoza/emul.ge/blob/8a63b8e1ed4b0ca43a32056d10d22cde7709085f/gulpfile.coffee)

Here is the full StackTrace if you need:

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
  at TypeError (<anonymous>:null:null)
  at DestroyableTransform.emit (events.js:74:15)
  at DestroyableTransform.onerror (_stream_readable.js:537:12)
  at DestroyableTransform.emit (events.js:95:17)
  at onwriteError (/path/to/project/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:250:10)
  at onwrite (/path/to/project/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:268:5)
  at WritableState.onwrite (/path/to/project/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
  at afterTransform (/path/to/project/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)
  at TransformState.afterTransform (/path/to/project/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /path/to/project/node_modules/gulp-minify-css/index.js:113:9
  at /path/to/project/node_modules/gulp-minify-css/index.js:36:7
  at whenSourceMapReady (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:89:16)
  at Object.whenDone (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:98:14)
  at processNext (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:105:13)
  at importFrom (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:79:10)
  at processNext (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:104:16)
  at inlineLocalResource (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:290:12)
  at inline (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:209:10)
  at importFrom (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:74:7)
  at ImportInliner.process (/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:36:10)
  at /path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:71:41
  at process._tickCallback (node.js:442:13)
```

_* I have changed the actual project path with `/path/to/project` for privacy reasons_

**Comment by Stichoza** [comment]
**Update:** The newer version which broke tasks was `v0.3.13` not `v0.3.12`. As I see breaking changes are after `v0.4`, so both `v0.3.13` and `v0.3.11` should work fine (but they don't).

**Comment by jonathanepollack** [comment]
I think, technically, breaking changes were originally introduced in v0.3.12, but I forgot to upgrade the version number -- really sorry about that.

Does you still have issues with version v0.4?

**Comment by Stichoza** [comment]
I haven't tried v0.4 yet, I froze my dependencies on v0.3.11.

**Comment by jonathanepollack** [comment]
Please try 4 and get back to me asap.

**Comment by Stichoza** [comment]
Updated to v0.4.2, error is the same (see stack trace above).

**Comment by jonathanepollack** [comment]
Oh man. No good. Let me look into this.

**Comment by jonathanepollack** [comment]
Also, are you sure you test v0.3.12 , and experienced no breakage?

**Comment by Stichoza** [comment]
I tried `v0.3.12` and still the same error. I can fix this by downgrading to `v0.3.11`
![screen shot 2015-01-26 at 18 10 44](https://cloud.githubusercontent.com/assets/1139050/5900860/ccbdb652-a586-11e4-8b43-d880797c40ee.png)

**Comment by jonathanepollack** [comment]
Cool. Can you go into `/path/to/project/node_modules/gulp-minify-css/index.js:113:9` and get me the log of the error object (and whatever else the callback was trying to return)?

**Comment by Stichoza** [comment]
In case of v0.3.12 ther was no line 113 (see the screenshot, that's line 87)

In case of v0.3.13 it's line 113 as you mentioned (and as it's stated in the stack trace in the issue description).

In both cases (line 87 and line 113) the code is `done(errors ? errors[0] : null, file);`

See full source here: https://github.com/jonathanepollack/gulp-minify-css/blob/e8dc2186b632e4696ed5b1dfa50ad597b815a0dd/index.js#L113

**Comment by jonathanepollack** [comment]
Yeah, I think I'm starting to see what's going on. Basically 047de32 made it in, without being tagged.

Let me see if I can roll in a patch on v0.3.x to fix this.

**Comment by Stichoza** [comment]
P.S In my case it's not a laravel app and I'm not using `laravel/elixir` I mentioned in https://github.com/laravel/elixir/pull/41. It's just a Node.js LoopBack app.

**Comment by jonathanepollack** [comment]
So the interesting thing is that you're getting the error event "error", which I believe is coming from inliner.

can you log for me `context.errors` at `/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:36` ?

**Comment by Stichoza** [comment]
Sorry for the late answer. The line 36 at inliner.js is `return importFrom(data, context);`

```javascript
ImportInliner.prototype.process = function (data, context) {
  var root = this.outerContext.options.root || process.cwd();

  context = override(context, {
    baseRelativeTo: this.outerContext.options.relativeTo || root,
    debug: this.outerContext.options.debug,
    done: [],
    errors: this.outerContext.errors,
    left: [],
    inliner: this.outerContext.options.inliner,
    rebase: this.outerContext.options.rebase,
    relativeTo: this.outerContext.options.relativeTo || root,
    root: root,
    sourceTracker: this.outerContext.sourceTracker,
    warnings: this.outerContext.warnings,
    visited: []
  });

  return importFrom(data, context);
};
```

**Comment by jonathanepollack** [comment]
Dude. I know what the line is. I want to know what the value of `context.errors` is for you.

**Comment by Stichoza** [comment]
Lol, sorry. Didn't read your comment carefully.

It's strange I run `npm update` and there are no more errors (and `context.errors` is an empty array I guess). Have you patched it already?

**Comment by jonathanepollack** [comment]
No patches, I've done nothing actually. Just twiddling my thumbs here.

**Comment by jonathanepollack** [comment]
If you're not still getting an error, I'm going to close this issue, ok?

**Comment by Stichoza** [comment]
I tested everything and works fine. I just removed `node_modules` folder and run `npm install` as I did usually during this conversation. Ok, let's close this issue.

**Comment by jonathanepollack** [comment]
@thepuzzlemaster can you log for me `context.errors` from `/path/to/project/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:36`?

**Comment by thepuzzlemaster** [comment]
Adding `console.log(context.errors);` to line 35 results in an empty array
[] being output to the console. Followed by the error.

**Comment by jonathanepollack** [comment]
Weird. Can you then log me the error object `errors` at `/path/to/project/node_modules/gulp-clean-css/index.js:112`?

**Comment by Stichoza** [comment]
The `context.error` was an empty array for me too ([comment above](https://github.com/jonathanepollack/gulp-minify-css/issues/61#issuecomment-71488497)), but it was when the error got fixed.

**Comment by thepuzzlemaster** [comment]
Assuming it's a typo, my installed modules don't have gulp-clean-css, but instead just clean-css.

clean-css/index.js is only one line, which exports `./lib/clean`

lib/clean.js has a function `minifyWithDebug` on line 110, which accepts a context argument. I attempted to log context.errors inside that function, but it never fires.

**Comment by jonathanepollack** [comment]
I'm sorry, I meant `gulp-minify-css`. I.e. **this** package.

**Comment by thepuzzlemaster** [comment]
Ahhh. 

`[ 'Broken @import declaration of "../bower_components/attribute-reflection-mixin/attribute-reflection-mixin.css"' ]`

**Comment by jonathanepollack** [comment]
Yeah, it can't find that file, which is why you're getting that error.

```js
if (!fs.existsSync(fullPath) || !fs.statSync(fullPath).isFile()) {
    context.errors.push('Broken @import declaration of "' + importedFile + '"');
    return processNext(context);
  }
```
from `clean-css/limb/imports/inliner.js:288`

**Comment by thepuzzlemaster** [comment]
Unfortunately, I didn't set up the build process for this app, and it's rather complex. I will look into why that file exists (assuming it does) in v0.3.11 and not in this version.

I would say, that surfacing that error would be mighty handy, though.

**Comment by jonathanepollack** [comment]
Basically after `v0.3.11` we introduced local inline imports -- which is why things are failing for you. If you don't want to process imports, you can supply the gulp plugin with the option `{processImport: false}`. (In fact, give that a shot and see if you everything works).

**Comment by thepuzzlemaster** [comment]
Yes, changing my option to false from true did stop the error, and everything appears to be working correctly.

**Comment by Stichoza** [comment]
Now it's getting even more strange. The error still occurred for me. Then I run `gulp` again and still the same error. I run `gulp` *third* time and everything worked.

I haven't changed even a single character in code.

**Comment by jonathanepollack** [comment]
@Stichoza You should just disable local import processing. You were actually using before v0.3.12, so this should cause any breakage.

In the meanwhile, I'm going to roll a patch that gives more descriptive errors.

**Comment by thepuzzlemaster** [comment]
Thanks for the help with this @jonathanepollack 
This makes sense.

**Comment by gemmastephen** [comment]
Setting {processImport: false} worked for me, thanks!

**Comment by jonathanepollack** [comment]
:+1:

**Comment by kiki-le-singe** [comment]
{processImport: false} works for me to, thanks!
