### ISSUE TITLE
Incomplete sources property in multi-step setup when using the base option in gulp.src

### ISSUE THREAD

**Issue by backflip** [jonathanepollack/gulp-minify-css#64]
I discovered a really weird issue in my setup (which includes sass as a preprocessing step): When specifying the ```base``` option in ```gulp.src```, the ```sources``` property of the map returned is missing the included files.

## General setup

Gulpfile.js:
```js
gulp.src('css/main.scss', {
	base: '.'
})
.pipe(sourceMaps.init())
.pipe(sass())
.pipe(minifyCSS())
.pipe(write);
```

main.scss:
```sass
@import "_partial";

body {
	color: red;
}
```

## Result

- Expected ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```
- Resulting ```sources``` of map: ```['css/main.scss']```

## Fixes

**1. Omitting the ```base``` option:**
- Expected ```sources``` of map: ```['_partial.scss', 'main.scss']```
- Resulting ```sources``` of map: ```['_partial.scss', 'main.scss']```

This is not an option since I'm in fact passing an array to ```gulp.src```.

**2. Removing the minification step:**
- Expected ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```
- Resulting ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```

Well, not really an option, too.

**3. Changing your plugin to pass the existing sourcemap [as a string](https://github.com/unic/gulp-minify-css/commit/4e6b5ec38a704c8eca5a45be490059e6f1b73a05#diff-168726dbe96b3ce427e7fedce31bb0bcL83):**
- Expected ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```
- Resulting ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```

I have added a test case to my fork: https://github.com/unic/gulp-minify-css/commit/4e6b5ec38a704c8eca5a45be490059e6f1b73a05

----------

Do you or @floridoo have any idea what's going on here?

**Comment by jonathanepollack** [comment]
Let start with the basic diagnostics: what version are you using? Does the source map example pattern (using gulp src maps) not work for you?

**Comment by backflip** [comment]
I'm using a fork of your repo which was updated yesterday, I guess it's 0.4.4. The example pattern works as long as I don't use the ```base``` option in ```gulp.src``` (see example in https://github.com/unic/gulp-minify-css/commit/4e6b5ec38a704c8eca5a45be490059e6f1b73a05#diff-55582a548247743b28d88aa1ff809961R94).

**Comment by jonathanepollack** [comment]
Can you go back to v0.4.0 and see if that works?

**Comment by backflip** [comment]
Same issue with v0.4.0

**Comment by jonathanepollack** [comment]
So it means the source-maps feature was never implemented to handle this,
then....

**Comment by jonathanepollack** [comment]
Alrighty, it looks like we should just go with your PR then!

**Comment by backflip** [comment]
@floridoo, are there any downsides to passing the whole sourcemap as a string to ```vinyl-sourcemaps-apply``` as suggested in https://github.com/unic/gulp-minify-css/commit/4e6b5ec38a704c8eca5a45be490059e6f1b73a05#diff-168726dbe96b3ce427e7fedce31bb0bcR83?

**Comment by backflip** [comment]
Okay, I'd suggest merging this. Sorry about the back and forth... :)

**Comment by backflip** [comment]
After doing some more digging: The issue seems to have to do with ```vinyl-sourcemaps-apply``` all the same.

## 1. Without ```base``` option
**Input to ```applySourceMap(file, sourceMap)```:**

```file.sourceMap``` :
```js
{ version: 3,
  sources: [ 'srcmap-sub/srcmap-sub.scss', 'sourcemap.scss' ],
  names: [],
  mappings: ';AAAA;EACE,AAAY;EACZ,AAAO;;ACET;EACE,AAAO;EACP,AAAW',
  file: 'sourcemap.css',
  sourcesContent: 
   [ null,
     '/*! Special Comment */\n\n@import "srcmap-sub/srcmap-sub.scss";\n\n.sourcemap {\n  color: green;\n  font-size: 20px;\n}\n' ] }
```

```sourceMap``` :
```js
{ version: 3,
  sources: [ 'sourcemap.css' ],
  names: [],
  mappings: ';AACA,WACE,kBAIA,YACA',
  file: 'sourcemap.css' }
```

**Output from ```applySourceMap(file, sourceMap)```:**

```file.sourceMap``` :
```js
{ version: 3,
  sources: [ 'srcmap-sub/srcmap-sub.scss', 'sourcemap.scss' ],
  names: [],
  mappings: ';AAAA,WACE,kBCIO,YACP',
  file: 'sourcemap.css',
  sourcesContent: 
   [ null,
     '/*! Special Comment */\n\n@import "srcmap-sub/srcmap-sub.scss";\n\n.sourcemap {\n  color: green;\n  font-size: 20px;\n}\n' ] }
```


## 2. With ```base``` option

**Input to ```applySourceMap(file, sourceMap)```:**

```file.sourceMap``` :
```js
{ version: 3,
  sources: 
   [ 'test/fixture/srcmap-sub/srcmap-sub.scss',
     'test/fixture/sourcemap.scss' ],
  names: [],
  mappings: ';AAAA;EACE,AAAY;EACZ,AAAO;;ACET;EACE,AAAO;EACP,AAAW',
  file: 'sourcemap.css',
  sourcesContent: 
   [ null,
     '/*! Special Comment */\n\n@import "srcmap-sub/srcmap-sub.scss";\n\n.sourcemap {\n  color: green;\n  font-size: 20px;\n}\n' ] }
```

```sourceMap``` :
```js
{ version: 3,
  sources: [ 'test/fixture/sourcemap.css' ],
  names: [],
  mappings: ';AACA,WACE,kBAIA,YACA',
  file: 'test/fixture/sourcemap.css' }
```

**Output from ```applySourceMap(file, sourceMap)```:**

```file.sourceMap``` :
```js
{ version: 3,
  sources: [ 'test/fixture/sourcemap.css' ],
  names: [],
  mappings: ';AACA,WACE,kBAIA,YACA',
  file: 'test/fixture/sourcemap.css',
  sourcesContent: [ null ] }
```

**Comment by backflip** [comment]
(Comment removed after realizing it was incorrect). I will stop spamming now, I promise.

**Comment by jonathanepollack** [comment]
This patch made it into `v0.4.5`.
