### ISSUE TITLE
When keepSpecialComments is not  0

### ISSUE THREAD

**Issue by dewald-laubscher** [jonathanepollack/gulp-minify-css#65]
So I don't forget to make a recreate able  process.

When minifyi runs on css that has comments (or I dont even know where the comments are coming from  after minification) and  I have css that start with [star], the all selector, then the logical outworking is no style because of /[star] being the result. I will recreate this and post that code here in a while.

**Comment by shinnn** [comment]
Any updates?

**Comment by dewald-laubscher** [comment]
@shinnn  Not on my side, I just removed the commented text entirely by enabling the option as per the specifications.

**Comment by shinnn** [comment]
@dewald-laubscher  Sorry, I still can't understand what you said...

// @jonathanepollack

**Comment by dewald-laubscher** [comment]
Sure thing...

When you have a stylesheet that starts with 
```scss
/**
  * some commented section
  */
* {
  //any styles
  border: none;
}
```
If you do not add the option {keepSpecialComments: 0} of the minifyCSS function then your stylesheet compiles as follow.
```scss
/**
  * some commented section
  */* {border:none;}
```
The effect of this will cause the css to be commented out. Therefore you lose all your styles as they are falling in the same line as the comment open ( /* ) operator.

My gulp task in coffee looks like this.

```coffee
gulp         = require "gulp"
minifyCSS    = require "gulp-minify-css"

gulp.task "minify", () ->
  gulp.src(["css/style.css"])
    .pipe minifyCSS({keepSpecialComments: 0})
    .pipe rename({suffix: '.min'})
    .pipe gulp.dest("css/style.min.css")
    .pipe gulp.dest('./')
```

**Comment by shinnn** [comment]
@dewald-laubscher 

I created a HTML to reproduce the problem, but I couldn't.

```html
<html>
<head>
<style>
/*!
  * some commented section
  */*{border:none}
</style>
</head>
<p>Hi</p>
</html>
```

`*{border:none}` is parsed as valid CSS rule.

![image](https://cloud.githubusercontent.com/assets/1131567/6559181/6fac550e-c6c4-11e4-9f48-819b9e3ff66a.png)

**Comment by shinnn** [comment]
@dewald-laubscher And you should read [*Regarding issues*](https://github.com/jonathanepollack/gulp-minify-css/tree/344938819bb3cecf73d16314a486a4e592403a81#regarding-issues) section in the README.

**Comment by dewald-laubscher** [comment]
@shinnn  thanks will do that.

**Comment by hellier** [comment]
You've referenced the above thread, but I can't see any relation to it? Combining properties into their shorthand, and this thread, that is.

**Comment by dewald-laubscher** [comment]
He means to say "And, please read Regarding issues section of the README."
