### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ai** [jonathanepollack/gulp-minify-css#73]
@shinnn Without Changelog I didn’t knoww what is in 0.5.1 release and is it safe to update?

**Comment by shinnn** [comment]
This project follows semver. There is no breaking changes between 0.5.0 and 0.5.1.

**Comment by ai** [comment]
But what error was fixed?

**Comment by shinnn** [comment]
Just a code refactoring.

> **80 additions** and **117 deletions**.

**Comment by ai** [comment]
Write it to `Changelog` file :)

**Comment by ai** [comment]
You released major `1.0.0` and still doesn’t have ChangeLog. Maybe I can help you? It is very important to have ChangeLog to every open surce project.

**Comment by jonathanepollack** [comment]
Not certain how important this is, for this project--as this project is just a wrapper around `clean-css`, it's API should only really change to deal with the `gulp` architecture--following what's changing should be fairly easy by reading the commit messages.

**Comment by ai** [comment]
Having a Changelog is a industry standard: 

http://keepachangelog.com/
http://marcgg.com/blog/2013/03/25/please-changelog-open-source/

`git log` is a bad format, because it contains many irrelevant to API changes commits.

**Comment by jonathanepollack** [comment]
fair enough.

Would you like to create a change log for us, then?

**Comment by ai** [comment]
I can create some examples file to show format, but I didn't understand even changes in 1.0.0.

**Comment by jonathanepollack** [comment]
That's fine. The links you dropped are pretty informative, no need to bother.
