### ISSUE TITLE
Move over to proper semver

### ISSUE THREAD

**Issue by jonathanepollack** [jonathanepollack/gulp-minify-css#74]
Perhaps we should bump this package to `v1.0.0` already, and treat minor and patch changes in the semver manner?

**Comment by shinnn** [comment]
@jonathanepollack 

I think we should fix some issues before releasing the first major version. #75 #76

**Comment by jonathanepollack** [comment]
Agreed. I just thought it'd be nice to put this on the roadmap. :-)

**Comment by shinnn** [comment]
Both #75 and #76 are fixed. Now we can release :star: :star2: v1.0.0 :star2: :star:.

**Comment by jonathanepollack** [comment]
:+1: :+1: :+1: :+1:

**Comment by jonathanepollack** [comment]
Do you want to do the honours?

**Comment by shinnn** [comment]
> Do you want to do the honours?

:ok:
