### ISSUE TITLE
Remove `cache` option

### ISSUE THREAD

**Issue by shinnn** [jonathanepollack/gulp-minify-css#75]
[The plugin guideline](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) says:

> Your plugin should only do **one thing**, and do it well.

File caching is not a part of clean-css.

There are some better solutions for caching on gulp file system.

* [gulp-cache](https://github.com/jgable/gulp-cache/)
* [gulp-newer](https://github.com/tschaub/gulp-newer)
* [gulp-cached](https://github.com/wearefractal/gulp-cached)

**Comment by shinnn** [comment]
@jonathanepollack What do you think about this?

**Comment by jonathanepollack** [comment]
I think you're right. It got rolled in a while ago due to convenience, but that was probably an oversight on my part.
