### ISSUE TITLE
combining properties into their shorthand 

### ISSUE THREAD

**Issue by hellier** [jonathanepollack/gulp-minify-css#77]
Would be great if you could incorporate https://github.com/frankmarineau/shrthnd.js

Input:

    body {
	font-size: 1em;
	line-height: 1.2em;
	font-family: Helvetica;
	font-weight: 300;
	font-style: italic;
    }

Output:

    body {
      font: italic 300 1em/1.2em Helvetica;
    }

**Comment by shinnn** [comment]
https://github.com/jonathanepollack/gulp-minify-css/issues/65#issuecomment-77888721
