### ISSUE TITLE
Bug about background

### ISSUE THREAD

**Issue by AMAID** [jonathanepollack/gulp-minify-css#78]
input:
`background:url("foo") top center`
output:
`background:url("foo")top center`

Missing a space between the "url" and other attributes.
This causes the background does not take effect when working on IE8(and blow)

**Comment by AMAID** [comment]
Sorry, I got it.My fault.

**Comment by think2011** [comment]
Hi, what should I do? @AMAID

**Comment by AMAID** [comment]
@think2011 readme里有个参数 兼容IE7、8的 一开始没看到 你去找找

**Comment by think2011** [comment]
@AMAID 谢谢哈！

**Comment by shinnn** [comment]
https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977
