### ISSUE TITLE
 + aSource + '" is not in the SourceMap

### ISSUE THREAD

**Issue by digisavvy** [jonathanepollack/gulp-minify-css#80]
I'm using gulp-sass and just a "few" other packages. I get this error when trying to use gulp-sourcemaps. I run gulp and my styles task errors out. I tried disabling autoprefixer and that doesn't work. As for the note about prefixer.scss not being in the sourcemap that's odd, because the file is present, I'm just not clear on exactly what's going on and hoping someone can shed some light here for me. As far as I know everything that should be there is there...

Thanks. =) 

Error after running gulp:
```
/Users/Alex/Documents/Websites/somelikeitneat.dev/wp-content/themes/somelikeitneat/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "/bower_components/bourbon/app/assets/stylesheets/addons/_prefixer.scss" is not in the SourceMap.
  at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/Alex/Documents/Websites/somelikeitneat.dev/wp-content/themes/somelikeitneat/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415:13)
  at SourceMapGenerator.<anonymous> (/Users/Alex/Documents/Websites/somelikeitneat.dev/wp-content/themes/somelikeitneat/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
```

Packages:
```
    "browser-sync": "^2.4.0",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-cache": "^0.2.8",
    "gulp-coffee": "^2.3.1",
    "gulp-combine-media-queries": "^0.1.0",
    "gulp-concat": "^2.5.2",
    "gulp-consolidate": "^0.1.2",
    "gulp-filter": "^2.0.2",
    "gulp-ignore": "^1.2.1",
    "gulp-imagemin": "^0.6.2",
    "gulp-jshint": "^1.9.4",
    "gulp-livereload": "^2.1.1",
    "gulp-load-plugins": "^0.6.0",
    "gulp-minify-css": "^1.0.0",
    "gulp-newer": "^0.3.0",
    "gulp-notify": "^2.2.0",
    "gulp-phpcs": "^0.4.0",
    "gulp-plumber": "^0.6.6",
    "gulp-rename": "^1.2.0",
    "gulp-rimraf": "^0.1.0",
    "gulp-ruby-sass": "^1.0.1",
    "gulp-run-sequence": "^0.3.2",
    "gulp-sass": "^1.3.3",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-swig": "^0.7.4",
    "gulp-uglify": "^0.3.2",
    "gulp-util": "^3.0.4",
    "gulp-wp-rev": "0.0.1",
    "gulp-zip": "^2.0.3",
    "swig": "^1.4.2"
```
Task:
```
gulp.task('styles', function () {
	return gulp.src([source+'sass/**/*.scss'])
		.pipe(plumber())
		.pipe(sourcemaps.init())
			.pipe(sass({
				// outputStyle: 'compressed',
				outputStyle: 'nested',
				precision: 10
			}))
		.pipe(sourcemaps.write({includeContent: false}))
		.pipe(sourcemaps.init({loadMaps: true}))
		.pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
		.pipe(sourcemaps.write('/sourcemaps'))
		.pipe(plumber.stop())
		.pipe(gulp.dest(source+'css'))
		.pipe(filter('**/*.css')) // Filtering stream to only css files
		.pipe(cmq()) // Combines Media Queries
		.pipe(reload({stream:true})) // Inject Styles when style file is created
		.pipe(rename({ suffix: '-min' }))
		.pipe(minifycss({keepBreaks:true}))
		.pipe(minifycss({ keepSpecialComments: 0 }))
		.pipe(gulp.dest(source+'css'))
		.pipe(reload({stream:true})) // Inject Styles when min style file is created
		.pipe(notify({ message: 'Styles task complete', onLast: true }))
});
```

**Comment by shinnn** [comment]
Can you create a small repository that can reproduce the error?

**Comment by shinnn** [comment]
OK I found [the repo](https://github.com/digisavvy/some-like-it-neat) you're working on but I couldn't reproduce the error.

```
$ git clone https://github.com/digisavvy/some-like-it-neat
$ cd some-like-it-neat
$ npm install
$ bower install
$ gulp styles
[21:00:04] Using gulpfile ~/username/some-like-it-neat-master/gulpfile.js
[21:00:04] Starting 'styles'...
[21:00:05] gulp-notify: [Gulp notification] Styles task complete
[21:00:05] Finished 'styles' after 528 ms
```

**Comment by youanden** [comment]
I had a similar issue trying to implement the gulp asset pipeline into ruby on rails.


My config looked like this:
```
  return gulp.src(config.src)
    .pipe(sourcemaps.init())
    .pipe(sass(config.settings))
    .on('error', handleErrors)
    .pipe(sourcemaps.write())
    .pipe(autoprefixer({ browsers: ['last 2 version'] }))
    .pipe(gulp.dest(config.dest))
    .pipe(browserSync.reload({stream:true}));
```

I first removed autoprefixer and that worked. Then I tried the following (making sure autoprefixer ran before sourcemaps were written):

```
  return gulp.src(config.src)
    .pipe(sourcemaps.init())
    .pipe(sass(config.settings))
    .on('error', handleErrors)
    .pipe(autoprefixer({ browsers: ['last 2 version'] }))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(config.dest))
    .pipe(browserSync.reload({stream:true}));
```

This resulted in the ever-pleasing: 
```
$ gulp sass
[19:11:47] Using gulpfile i:\current_projects\as\app\gulpfile.js
[19:11:48] Starting 'sass'...
[19:11:48] Finished 'sass' after 184 ms
```

I see that you're running sourcemaps twice. I'm no expert, so I'm not sure if that configuration is yielding  the intended results.

**Comment by shinnn** [comment]
@youanden Here is [gulp-minify-css](https://github.com/jonathanepollack/gulp-minify-css) repo.

**Comment by Lefthandmedia** [comment]
I'm getting the same error. the file that is not  'In the SourceMap' is a symlink on OSX.
Could that be the reason? and can it be fixed?

**Comment by shinnn** [comment]
@Lefthandmedia Can you create a small repository that can reproduce the error?

**Comment by Laykou** [comment]
Hi, I would like to report the same error for *.js file. I get the error on Ubuntu 14.04 however on Windows 7 it works normally without any error. I'm sorry, I cannot share the repo, since it's private and commercial project, but maybe the info about Linux and Windows will help.

My error:

```
/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/node_modules/source-map/lib/source-map/source-map-consumer.js:415
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "app.bootstrap.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/node_modules/source-map/lib/source-map/source-map-consumer.js:415:13)
    at SourceMapGenerator.<anonymous> (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at SourceMapper.applySourceMap (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/build/es5/generate-sourcemap.js:92:20)
    at generateSourcemap (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/build/es5/generate-sourcemap.js:112:20)
    at ngAnnotate (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:1098:9)
    at DestroyableTransform.flush [as _flush] (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/index.js:44:24)
    at DestroyableTransform.<anonymous> (/home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:180:16)
```

**Comment by shinnn** [comment]
> ```
> /home/laykou/Projects/project_name/node_modules/browserify-ngannotate/node_modules/ng-annotate/node_modules/source-map/lib/source-map/source-map-consumer.js:415
> ```

@Laykou That's not related to this project gulp-minify-css, I think.

**Comment by mik-laj** [comment]
@shinnn 
I also have a problem. 
I created a small project, that can reproduce the error :-) 
https://github.com/mik-laj/gulp-minify-css-error
To init project
``bower install 
sudo npm install
``

**Comment by depiction** [comment]
I'm also experiencing the same issue; not sure why this was closed.

**Comment by jrehwaldt** [comment]
I forked @mik-laj's project and recreated the issue using LESS instead of SASS. This removes the external Ruby/SASS dependency and ensures a simple ``bower install && npm install && gulp`` really does the trick.

Have a look here: https://github.com/jrehwaldt/gulp-minify-css-error

Please reopen this bug and tell us how we can assist further.

**Comment by storafrid** [comment]
+1 as I'm running into this issue as well. Replacing gulp-minify-css with gulp-uglifycss resolves the issue. The only SCSS I'm loading is the Zurb Foundation library.

Should this issue be closed, @shinnn ?

**Comment by shinnn** [comment]
@storafrid Why do you think that is a gulp-minify-css issue?

**Comment by storafrid** [comment]
Your question doesn't seem to be very helpful. How is it not a gulp-minify-css issue that I get this error when running gulp-minify-css? The same command works with gulp-uglifycss.

Feel free to ask your actual questions that helps us move forward with the issue. Meanwhile I am using gulp-uglifycss.

**Comment by shinnn** [comment]
I've investigated for a while and finally I found the root cause, [this gulp-sourcemaps behavior](https://github.com/floridoo/gulp-sourcemaps/pull/11#issuecomment-47792254).

gulp-less and gulp-sass should be fixed in a way equivalent to https://github.com/contra/gulp-coffee/pull/42.

Now, I can confidently say, this is not a gulp-minify-css issue. https://github.com/floridoo/gulp-sourcemaps/issues/108#issuecomment-84876286 was a complete misdirection.

**Comment by storafrid** [comment]
Good job with the investigation! Should an issue in the gulp-sourcemaps project be created, or what is the proposed way forward in order to resolve this?

**Comment by shinnn** [comment]
> Should an issue in the gulp-sourcemaps project be created

Probably, no. It's already enough discussed on that repo.

> what is the proposed way forward in order to resolve this?

The easiest way is adding `sourceRoot` option to https://github.com/jrehwaldt/gulp-minify-css-error/blob/0f178e3506b94cda48df34d9af2f487f579b3d42/gulpfile.js#L23:

```js
.pipe(sourcemaps.write({sourceRoot}))
```

Or, disable gulp-minify-css's `sourceMap` option.

```js
.minifyCss({sourcemap: false})
```

**Comment by jrehwaldt** [comment]
https://github.com/plus3network/gulp-less/issues/166#issuecomment-150491964 FYI: I indeed see an issue with latest `gulp-less@3.0.3` causing issues with sourcemaps. But while I could get `gulp-postcss+csswring` and `gukp-cssnano` play nicely with versions pre-3.0.3, I never got a correct sourcemap using `gulp-minify-css`.

**Comment by shinnn** [comment]
@jrehwaldt Did you read https://github.com/murphydanger/gulp-minify-css/issues/80#issuecomment-148848226 before submitting a new comment?

**Comment by shinnn** [comment]
An awesome pull request to fix this problem from @jrehwaldt, the CSS and sourcemap expert, is always appreciated.

**Comment by jrehwaldt** [comment]
I didn't mean to offend you and just wanted to let you know. Sorry, that that's not appreciated. And no, I am neither an expert nor would I be able to create awsome pull requests. If I could, I'd do it.

And yes, I tried your two solution proposals. The first I couldn't get to work as it seems incomplete (or I'm just not getting what I should set as `sourceRoot`) and the second turns sourcemaps off. Either way, I never doubted your findings and they might be totally correct. But as a matter of fact I could not get correct sourcemaps with this library (which of course might be my fault).
