### ISSUE TITLE
Set advanced and aggresive optimization to false by default.

### ISSUE THREAD

**Issue by outpunk** [jonathanepollack/gulp-minify-css#84]
These optimizations are not safe, it would be better to turn them off by default. For example, it can break flexbox.

The desired CSS: we have `display: flex` as a result. 
![](http://img.madyankin.name/Bo2Ta.png)

The minified CSS: we have `display: -webkit-box` as a result.
![](http://img.madyankin.name/P7uNq.png)

**Comment by shinnn** [comment]
I cannot reproduce the problem.

```js
'use strict';

var File = require('vinyl');
var gulpMinifyCss = require('./');

gulpMinifyCss()
  .on('data', function(file) {
    console.log(file.contents.toString()); //=> a{display:flex}
  })
  .end(new File({
    contents: new Buffer('a {\n  display: flex\n}\n')
  }));
```

Seems to be an issue with other plugin(s).

**Comment by shinnn** [comment]
And, please read [*Regarding issues*](https://github.com/jonathanepollack/gulp-minify-css/tree/344938819bb3cecf73d16314a486a4e592403a81#regarding-issues) section of the README.
