### ISSUE TITLE
IE Bug ".4" needs to be "0.4"

### ISSUE THREAD

**Issue by joshmedeski** [jonathanepollack/gulp-minify-css#85]
I'm faced with a IE bug

```
border-color: rgba(255,255,255,.4)transparent transparent;
```

The '.4' value needs to be '0.4' to work in IE. Is there a setting to keep this data in place after minifying the file?

**Comment by shinnn** [comment]
https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977
