### ISSUE TITLE
I have a suggestion for ‘compatibility’ Configuration

### ISSUE THREAD

**Issue by noonhorse** [jonathanepollack/gulp-minify-css#87]
Not long ago, I use gulp to do the construction of compression, delete the default ie6-8 hack css,
Back to see the need to separately add ie comments

**Comment by shinnn** [comment]
https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977

I don't want gulp-minify-css to have different defaults from clean-css's.
