### ISSUE TITLE
processImport flag default of true results in timeout

### ISSUE THREAD

**Issue by the-simian** [jonathanepollack/gulp-minify-css#93]
An example error:
```sh
Broken @import declaration of "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,300,700,800,400,600" - timeout
```

I can get around this by setting the processImport flag, to false. I notice on the css-min repository, they state a callback is necessary to make remote process imports work correctly. Aside from simply turning off `processImport`, is there a more elegant or correct way to fix this? 
Can you change the timoute or provide a callback via this gulp interface? 
Is simply setting this to false really the only fix?

I'd flag this as low priority, since there is a workaround, and it also might just be misusing the tool. this also might be better filed with `clean-css`. Thanks for any input you have!

**Comment by shinnn** [comment]
I cannot reproduce the error.

```js
'use strict';

var File = require('vinyl');
var gulpMinifyCss = require('./');

gulpMinifyCss()
  .on('data', function(file) {
    console.log(file.contents.toString()); //=> @font-face{font-family:'Open Sans';font-style:normal; ...
  })
  .end(new File({
    contents: new Buffer('@import "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,300,700,800,400,600";'
)
  }));
```

Could you run these commands and show us the result?

```
$ node -v
$ npm -v
$ npm ls gulp-minify-css
```

**Comment by the-simian** [comment]
node version: 0.10.33
npm: 2.3.0
gulp-minify-css : 1.1.0

**Comment by shinnn** [comment]
You're using too older node. Though it's not directly related to this issue, I recommend updating node to v0.12.2.

> Can you change the timoute

https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977 Contact the author of [clean-css](https://github.com/jakubpawlowicz/clean-css) for `timeout` option if you want. Currently clean-css doesn't support it.

> provide a callback

Use Stream's `.on` method instead.
