### ISSUE TITLE
"inherit" values are getting mangled

### ISSUE THREAD

**Issue by tjwebb** [jonathanepollack/gulp-minify-css#94]
When running my css through gulp-minify-css, some my css is getting corrupted. I end up with this:

```
    background: inherit inherit/inherit inherit inherit inherit;
    border: inherit inherit inherit;
```

The original values are:

```
    background: inherit;
    border: inherit;
```

Everything else seems to work fine.

**Comment by ericcholis** [comment]
I've also experienced this, downgrading to 1.0.x or 0.5.x didn't fix the issue.

**Comment by shinnn** [comment]
https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977
