### ISSUE TITLE
Compiled CSS included in Sources gulp-sourcemap list

### ISSUE THREAD

**Issue by sjmcpherso** [jonathanepollack/gulp-minify-css#97]
Hi, I wasnt exactly sure where to post this but the issue occurs when using a combination of gulp-sourcemaps, gulp-less & gulp-minify-css whereby the compiled CSS is listed in the source map i.e. {"version":3,"sources":["../generic/jquery.jqzoom.less","compiled.css","theme.less","../generic/jquery.fancybox.less"... 

If I remove the MinifyCss function the compiled.css file is not included in the sources as expected, but  of course I lose the functionality of your helpful plugin.

My task is:
gulp.task('less', function () {
  gulp.src('../master.less')
    .pipe(sourcemaps.init())
    .pipe(less())
    .pipe(minifyCss({compatibility: 'ie8'}))
    .pipe(sourcemaps.write('./maps', {debug: true}))
    .pipe(gulp.dest('docs/themes/'));
});

And Dependencies:

 "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-less": "^3.0.3",
    "gulp-minify-css": "^1.1.1",
    "gulp-sourcemaps": "^1.5.2",
  }

Your thoughts or a workaround appreciated

**Comment by shinnn** [comment]
Can you create a small repository that can reproduce the problem?

**Comment by sjmcpherso** [comment]
In the process of creating a repository for you I found what was causing the issue, it was a open comment in a less files that I was including below and then a catch all CSS selector in another less file

/*********************************************************
Comment
/*********************************************************/

*{box-sizing: border-box;}


I've added a repository if you wish to investigate any further at https://github.com/sjmcpherso/gulp-minify-issue

Thanx
