### ISSUE TITLE
font-face rule with quotes

### ISSUE THREAD

**Issue by priley86** [jonathanepollack/gulp-minify-css#98]
Something seems to have changed between 1.0.0 and 1.1.1 with the way font-face rules get minified. I have the following rule:

```
@font-face {
	font-family: 'Univers Cn Lt';
	src: url('../fonts/UniversLTStd-LightCn.eot');
	src: url('../fonts/UniversLTStd-LightCn.eot?#iefix') format('embedded-opentype'), url('../fonts/UniversLTStd-LightCn.woff') format('woff'), url('../fonts/UniversLTStd-LightCn.ttf') format('truetype'), url('../fonts/UniversLTStd-LightCn.svg#Univers Cn Lt') format('svg');
	font-weight: 200;
	font-style: normal;
}
```
This will minify correctly in 1.0.0 with the single quotes included, '../fonts/UniversLTStd-LightCn.svg#Univers Cn Lt', but in 1.1.0 this compiles without quotes and causes a font load failure.

Is there some arg to prevent this?

**Comment by shinnn** [comment]
https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977
