### ISSUE TITLE
IE8 does not read compressed background property

### ISSUE THREAD

**Issue by yomotsu** [jonathanepollack/gulp-minify-css#99]
gulp-minify-css will remove necessary space after url() function in CSS. like
```
background:url(../images/sprite_01.png)no-repeat;
```

it should be

```
background:url(../images/sprite_01.png) no-repeat;
                                       ^
```
otherwise, IE8 does not read whole background property

**Comment by tomaszstrzelec87** [comment]
You have to use the parameter 'compatibility' with value 'ie8'.

var minifyCss = require('gulp-minify-css'),
minifyCss({compatibility: 'ie8'})

**Comment by shinnn** [comment]
@tomaszstrzelec87 is right.

I always reply just like https://github.com/jonathanepollack/gulp-minify-css/issues/82#issuecomment-87196977 when I receive the [clean-css](https://github.com/jakubpawlowicz/clean-css) issue in this project. We'd be very happy if you could read at least the top of README before opening new issues.

However, thanks you for trying to contribute the open source project, @yomotsu.
